services:
  app:
    build: .
    image: take-home-test
    container_name: take-home-test
    restart: unless-stopped
    working_dir: /var/www/
    volumes:
      - ./:/var/www
      - ./docker-compose/php/php.ini:/usr/local/etc/php/php.ini
    ports:
      - 3002:80
